"use client";

import Link from "next/link";
import { Check, LockKeyhole, MessageCircle, Sparkles, Star } from "lucide-react";
import { Badge, Card } from "@/components/ui/card";
import { LanguageSwitcher } from "@/components/ui/language-switcher";
import { categories, course, milestones, payments } from "@/lib/content/config";
import { useLanguage } from "@/components/providers/language-provider";

const telegramUrl = process.env.NEXT_PUBLIC_TELEGRAM_CHAT_URL || "#community";

export function LandingPageContent({ stats, milestoneCounts }: { stats: { lessons: number; phrases: number; exams: number }; milestoneCounts: Record<string, number> }) {
  const { language } = useLanguage();
  const fr = language === "fr";
  const t = fr ? FR : RU;
  const benefits = fr ? BENEFITS_FR : BENEFITS_RU;
  const startHref = fr ? "/lesson/1" : "/learn";
  return <div className="min-h-dvh bg-background">
    <header className="sticky top-0 z-40 border-b border-line bg-surface/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8">
      <Link href="/" className="flex shrink-0 items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-sm font-black text-primary-contrast">ES</span><span><b className="block">Español Real</b><small className="block font-semibold text-muted">{t.brand}</small></span></Link>
      <nav className="hidden gap-6 text-sm font-bold text-muted md:flex"><a href="#structure">{t.program}</a><a href="#method">{t.method}</a><a href="#pricing">{t.pricing}</a><a href="#community">{t.community}</a></nav>
      <div className="flex items-center gap-2"><LanguageSwitcher /><Link href={startHref} className="inline-flex h-10 items-center rounded-full bg-primary px-4 text-sm font-extrabold text-white">{t.start}</Link></div>
    </div></header>
    <main>
      <section className="relative overflow-hidden bg-surface"><div aria-hidden className="hero-skew absolute right-[-8%] top-0 h-full w-[49%] opacity-90" /><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.04fr_.96fr] lg:px-8 lg:py-24">
        <div className="flex flex-col items-start justify-center"><Badge tone="primary"><Sparkles className="h-3.5 w-3.5" /> {t.badge}</Badge><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">{t.hero}<span className="block text-primary">{t.accent}</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted sm:text-xl">{t.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={startHref} className="inline-flex h-14 items-center rounded-full bg-primary px-7 text-base font-extrabold text-white">{t.start}</Link><Link href="/learn/settings#premium" className="inline-flex h-14 items-center gap-2 rounded-full border-2 border-primary px-7 text-base font-extrabold text-primary">{t.unlock} {payments.starsPrice} <Star className="h-4 w-4 fill-current" /></Link></div><p className="mt-4 text-sm text-muted">{course.freeLessonCount} {t.free}</p><div className="mt-10 grid w-full max-w-xl grid-cols-3 border-t border-line pt-6"><Stat value={stats.lessons} label={t.lessons} /><Stat value={stats.phrases} label={t.phrases} /><Stat value={stats.exams} label={t.exams} /></div></div>
        <div className="flex flex-col justify-center gap-5 lg:pl-10"><Card className="p-7 shadow-lg"><p className="text-xs font-extrabold uppercase tracking-widest text-muted">{t.example}</p><p className="mt-3 text-2xl font-black text-primary sm:text-3xl">Me pones un café con leche, por favor</p><p className="mt-3 text-sm leading-6 text-muted">{t.exampleText}</p></Card><Card className="p-7 shadow-lg"><p className="text-xs font-extrabold uppercase tracking-widest text-muted">{t.map}</p><ul className="mt-4 grid grid-cols-2 gap-2 text-sm font-bold">{milestones.slice(0, 6).map(m => <li key={m.id} className="flex gap-2 rounded-xl bg-background px-3 py-3"><span>{m.emoji}</span><span>{fr ? frMilestone(m.id).title : m.title}</span></li>)}</ul></Card></div>
      </div></section>
      <section id="method" className="bg-background py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-black sm:text-4xl">{t.why}</h2><p className="mt-3 text-muted">{t.whyText}</p><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(b => <Card key={b.title} className="p-6"><span className="text-3xl">{b.emoji}</span><h3 className="mt-4 text-lg font-black">{b.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{b.text}</p></Card>)}</div></div></section>
      <section id="structure" className="bg-surface py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><h2 className="text-3xl font-black sm:text-4xl">{t.structure}</h2><p className="mt-3 text-muted">{stats.lessons} {t.lessons}, {stats.phrases} {t.phrases}, {stats.exams} {t.exams}</p></div><Link href="/learn/lessons" className="font-extrabold text-primary">{t.allLessons} →</Link></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{milestones.map((m, i) => { const item = frMilestone(m.id); return <Card key={m.id} className="flex min-h-52 flex-col p-6"><div className="flex items-center justify-between"><span className="text-3xl">{m.emoji}</span><Badge tone={i === 0 ? "primary" : undefined}>{i === 0 ? `${t.stage} ${i + 1}` : <><LockKeyhole className="h-3.5 w-3.5" /> Premium</>}</Badge></div><h3 className="mt-5 text-lg font-black">{fr ? item.title : m.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{fr ? item.description : m.description}</p><p className="mt-auto pt-4 text-xs font-bold text-muted">{milestoneCounts[m.id] ?? 0} {t.lessons}</p></Card> })}</div><div className="mt-7 flex flex-wrap gap-2">{categories.map(c => <Badge key={c.id}>{c.emoji} {fr ? CATEGORY_FR[c.id] : c.labelRu}</Badge>)}</div></div></section>
      <section id="pricing" className="bg-background py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-black sm:text-4xl">{t.pricing}</h2><p className="mt-3 text-muted">{t.premiumText} {payments.starsPrice} ⭐ {t.inTelegram}</p><div className="mt-9 grid gap-5 lg:grid-cols-2"><Plan title={t.freeTitle} price="0 ⭐" features={t.freeFeatures} cta={t.start} href="/learn" /><Plan primary title="Premium" price={`${payments.starsPrice} ⭐`} features={t.premiumFeatures} cta={`${t.unlock} ${payments.starsPrice} ⭐`} href="/learn/settings#premium" /></div></div></section>
      <section id="community" className="bg-surface py-16 sm:py-20"><div className="mx-auto flex max-w-4xl flex-col items-center px-4 text-center"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#229ED9]/10 text-[#229ED9]"><MessageCircle /></div><h2 className="mt-5 text-3xl font-black sm:text-4xl">{t.communityTitle}</h2><p className="mt-3 max-w-2xl leading-7 text-muted">{t.communityText}</p><a href={telegramUrl} className="mt-7 inline-flex h-12 items-center gap-2 rounded-full bg-[#229ED9] px-6 font-extrabold text-white"><MessageCircle className="h-5 w-5" /> {t.join}</a></div></section>
    </main>
    <footer className="border-t border-line bg-surface"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-8 sm:grid-cols-3"><div><b>Español Real</b><p className="mt-2 text-sm text-muted">{t.brand}</p></div><div><b>{t.sections}</b><ul className="mt-3 space-y-2 text-sm text-muted"><li><Link href="/learn">{t.dashboard}</Link></li><li><Link href="/learn/lessons">{t.lessons}</Link></li><li><Link href="/learn/map">{t.map}</Link></li></ul></div><div><b>{t.product}</b><ul className="mt-3 space-y-2 text-sm text-muted"><li><a href="#pricing">{t.pricing}</a></li><li><Link href="/learn/settings#premium">{t.payment}</Link></li><li><a href="#community">{t.community}</a></li></ul></div></div><p className="mt-8 border-t border-line pt-5 text-xs text-muted">© {new Date().getFullYear()} Español Real. {t.copyright}</p></div></footer>
  </div>;
}

function Stat({ value, label }: { value: number; label: string }) { return <div className="text-center"><b className="text-2xl">{value}</b><small className="block text-muted">{label}</small></div>; }
function Plan({ title, price, features, cta, href, primary }: { title: string; price: string; features: string[]; cta: string; href: string; primary?: boolean }) { return <Card className={`flex flex-col p-7 ${primary ? "border-2 border-primary bg-primary text-white" : ""}`}><h3 className="text-xl font-black">{title}</h3><p className="mt-4 text-4xl font-black">{price}</p><ul className="mt-6 space-y-3 text-sm">{features.map(f => <li key={f} className="flex gap-2"><Check className="h-4 w-4 shrink-0" />{f}</li>)}</ul><Link href={href} className={`mt-8 inline-flex h-14 items-center justify-center rounded-full px-6 font-extrabold ${primary ? "bg-white text-primary" : "border-2 border-primary text-primary"}`}>{cta}</Link></Card>; }

const BENEFITS_RU = [{ emoji: "🗣️", title: "Реальные разговоры", text: "Только фразы, которые слышно в Испании — без лишней академической теории." }, { emoji: "📅", title: "Ежедневные ситуации", text: "Квартира, кофе, продукты, автобус, врач, банк, документы и работа." }, { emoji: "✏️", title: "Авторский метод", text: "Уроки построены вокруг живых фраз, примеров и комментариев автора." }, { emoji: "🔄", title: "Обучение через повторение", text: "Ошибки возвращаются в повторении, чтобы фразы закреплялись надолго." }, { emoji: "⚡", title: "Легко и быстро", text: "Короткие занятия, которые удобно проходить каждый день." }, { emoji: "🧳", title: "Для эмигрантов и путешественников", text: "Испанский для реальной жизни в Испании." }];
const BENEFITS_FR = [{ emoji: "🗣️", title: "Des conversations réelles", text: "Les phrases que l'on entend en Espagne, sans théorie scolaire superflue." }, { emoji: "📅", title: "Des situations quotidiennes", text: "Logement, café, courses, bus, médecin, banque, papiers et travail." }, { emoji: "✏️", title: "Une méthode d'auteur", text: "Des phrases vivantes, des exemples et des explications claires." }, { emoji: "🔄", title: "Apprendre par révision", text: "Les erreurs reviennent au bon moment pour ancrer les phrases." }, { emoji: "⚡", title: "Simple et rapide", text: "Des séances courtes, faciles à suivre chaque jour." }, { emoji: "🧳", title: "Pour vivre et voyager", text: "De l'espagnol pour la vraie vie en Espagne." }];
const CATEGORY_FR: Record<string, string> = { "daily-life": "Vie quotidienne", housing: "Logement", restaurant: "Café et restaurant", shopping: "Courses", transport: "Transports", health: "Médecin et santé", bank: "Banque", government: "Documents", police: "Police", "social-worker": "Service social", work: "Travail", social: "Amis et échanges", school: "École" };
function frMilestone(id: string) { return FR_MILESTONES[id] ?? { title: id, description: "" }; }
const FR_MILESTONES: Record<string, { title: string; description: string }> = { "first-days": { title: "Les premiers jours en Espagne", description: "Saluer, poser une question, faire répéter et réussir sa première conversation." }, housing: { title: "S'installer dans un logement", description: "Comprendre la location, le contrat et signaler un problème." }, coffee: { title: "Commander un café", description: "Commander au bar comme les habitants." }, groceries: { title: "Faire les courses", description: "Supermarché, marché, poids et monnaie sans stress." }, transport: { title: "Prendre le bus", description: "Métro, bus, taxi et cercanías." }, doctor: { title: "Aller chez le médecin", description: "Prendre rendez-vous et comprendre une ordonnance." }, bank: { title: "Ouvrir un compte", description: "Carte, cajero, virements et recibos." }, documents: { title: "Déposer les documents", description: "NIE, empadronamiento et démarches." }, work: { title: "Passer un entretien", description: "CV, entretien, contrat et nómina." }, friends: { title: "Se faire des amis", description: "Invitations et langage vivant." }, belonging: { title: "Se sentir chez soi", description: "Vivre en Espagne pour de vrai." } };
const RU = { brand: "Живой испанский", program: "Программа", method: "Метод", pricing: "Цена", community: "Сообщество", start: "Начать бесплатно", badge: "Курс по авторскому учебнику", hero: "Learn Real Spanish", accent: "Spoken in Spain", heroText: "Учите реальные фразы вместо грамматики. От «Me cuentas» до собеседования — только то, что нужно в Испании.", unlock: "Разблокировать за", free: "уроков бесплатно · без карты · без регистрации", lessons: "уроков", phrases: "фраз", exams: "экзаменов", example: "Пример фразы", exampleText: "Мне кофе с молоком, пожалуйста — так заказывают в Испании.", map: "Карта адаптации", why: "Почему это работает", whyText: "Фокус на том испанском, который нужен в реальной жизни в Испании.", structure: "Структура курса", allLessons: "Все уроки", stage: "Этап", premiumText: "Premium — единоразовая покупка за", inTelegram: "в Telegram.", freeTitle: "Бесплатно", freeFeatures: ["Первые уроки", "Карточки и упражнения", "Без регистрации"], premiumFeatures: ["Все уроки", "Система повторения", "Экзамены и сертификат"], communityTitle: "Сообщество в Telegram", communityText: "Общайтесь, задавайте вопросы по испанскому и практикуйте живые фразы вместе с другими учениками.", join: "Присоединиться к чату", sections: "Разделы", dashboard: "Дашборд", product: "Продукт", payment: "Оплата Stars", copyright: "Учебные материалы принадлежат автору и защищены авторским правом." };
const FR = { brand: "L'espagnol vivant", program: "Programme", method: "Méthode", pricing: "Tarifs", community: "Communauté", start: "Commencer gratuitement", badge: "Cours basé sur une méthode d'auteur", hero: "Apprendre l'espagnol", accent: "de façon pratique et naturelle", heroText: "Apprenez des phrases réelles plutôt que de mémoriser de la grammaire. De «Me cuentas» à l'entretien d'embauche : seulement ce dont vous avez besoin en Espagne.", unlock: "Débloquer pour", free: "leçons gratuites · sans carte · sans inscription", lessons: "leçons", phrases: "phrases", exams: "examens", example: "Exemple de phrase", exampleText: "Un café au lait, s'il vous plaît : c'est ainsi qu'on commande en Espagne.", map: "Parcours d'adaptation", why: "Pourquoi ça marche", whyText: "L'espagnol dont vous avez réellement besoin pour vivre en Espagne.", structure: "Structure du cours", allLessons: "Toutes les leçons", stage: "Étape", premiumText: "Premium — paiement unique de", inTelegram: "dans Telegram.", freeTitle: "Gratuit", freeFeatures: ["Premières leçons", "Cartes et exercices", "Sans inscription"], premiumFeatures: ["Toutes les leçons", "Système de révision", "Examens et certificat"], communityTitle: "Communauté Telegram", communityText: "Échangez, posez vos questions et pratiquez des phrases vivantes avec les autres apprenants.", join: "Rejoindre le chat", sections: "Rubriques", dashboard: "Accueil", product: "Produit", payment: "Paiement Stars", copyright: "Les supports pédagogiques appartiennent à l'auteur et sont protégés par le droit d'auteur." };
