"use client";
import { useEffect, useState } from "react";
import { shareNetworks } from "@/components/share/share-button";
import { parseTeacherSocialLinks, type TeacherSocialLinks } from "@/lib/teacher-socials";
export function TeacherSocialSettings() {
 const [links,setLinks]=useState<TeacherSocialLinks>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;void fetch("/api/teacher/settings",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(active)setLinks(parseTeacherSocialLinks(data.links)??{})},()=>{if(active){setFailed(true);setNotice("Не удалось загрузить настройки. Обновите страницу перед сохранением.")}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(){setBusy(true);setNotice("");try{const response=await fetch("/api/teacher/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({links})});const data=await response.json();if(!response.ok)throw Error(data.error);setLinks(data.links);setNotice("Ссылки сохранены")}catch(e){setNotice(e instanceof Error?e.message:"Не удалось сохранить")}finally{setBusy(false)}}
 return <section className="mt-8 space-y-4 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm" aria-label="Мои соцсети"><h2 className="text-lg font-bold">Мои соцсети</h2><p className="text-sm leading-6 text-stone-600">Добавьте профили или каналы, где публикуете посты. Они появятся в генераторе после входа. Публикацию вы подтверждаете в самой соцсети.</p><form onSubmit={e=>{e.preventDefault();void save()}} className="grid gap-4 sm:grid-cols-2">{shareNetworks.map(({name})=><label key={name} className="text-sm font-bold">{name=== "Вконтакте"?"ВКонтакте":name}<input type="url" value={links[name]??""} maxLength={2048} disabled={loading||busy||failed} placeholder="https://…" className="mt-2 block min-h-11 w-full rounded-xl border border-stone-200 px-3 font-normal" onChange={e=>setLinks({...links,[name]:e.target.value})}/></label>)}<button type="submit" disabled={loading||busy||failed} className="min-h-11 rounded-full bg-[#9E2A2B] px-5 py-3 font-bold text-white disabled:opacity-50 sm:col-span-2">{loading?"Загружаем настройки…":busy?"Сохраняем…":"Сохранить ссылки"}</button></form>{notice&&<p role="status" className="text-sm">{notice}</p>}</section>;
}
