const {chromium}=require('playwright');const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
function load(path){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require});return exports}
const model=load('src/lib/teacher-posts/model.ts'),examples=load('src/lib/teacher-posts/examples.ts').wowExamples,templates=load('src/server/teacher-posts/templates.ts');const post=templates.templatePost({...model.emptyDraft,sourceText:examples[1].sourceText});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:JSON.parse(process.env.PLAYWRIGHT_CHROMIUM_ARGS||'[]')}:{})});try{
 const base=process.argv[2]||'http://127.0.0.1:3100';const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await context.route('https://**/*',r=>r.abort());
 await context.route('**/api/telegram/session',r=>r.fulfill({json:{ok:true,configured:true,botUsername:'test',user:{telegramId:123,firstName:'QA'},premium:{active:false},orders:[]}}));
 await context.route('**/api/teacher/posts/generate',r=>r.fulfill({json:{post,cta:null,mode:'mock'}}));let publications=0;
 await context.route('**/api/teacher/posts/share',r=>{const b=r.request().postDataJSON();assert.ok(b.image.startsWith('data:image/jpeg;base64,')&&b.image.length>1000);assert.equal(b.post.title,post.title);const id='00000000-0000-4000-8000-'+String(++publications).padStart(12,'0');return r.fulfill({status:201,json:{id,url:base+'/p/'+id,imageUrl:base+'/media/posts/'+id+'/og.jpg',pinterestImageUrl:base+'/media/posts/'+id+'/pin.jpg'}})});
 await context.addInitScript(()=>{window.shareCalls=[];window.opened=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copied=text;window.shareCalls.push('copy')}}});Object.defineProperty(navigator,'canShare',{value:()=>true,configurable:true});Object.defineProperty(navigator,'share',{value:async data=>{window.shareCalls.push({file:data.files?.[0]?.type,name:data.files?.[0]?.name,text:data.text});if(window.cancelShare)throw new DOMException('cancel','AbortError')},configurable:true});window.open=(url)=>{window.opened.push(url);return {opener:null,document:{title:'',body:{textContent:''}},location:{replace:url=>window.opened.push(url)},close:()=>{}}};});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/teacher/posts/new');await page.getByRole('button',{name:'Деньги',exact:true}).click();await page.getByRole('button',{name:'Сгенерировать WOW-пост',exact:true}).click();const section=page.getByRole('region',{name:'Поделиться',exact:true});await section.waitFor();await section.getByRole('button',{name:'Скачать картинку',exact:true}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Скачать картинку'&&!b.disabled));
 const progress='espanol-real:progress:v1',before=await page.evaluate(k=>localStorage.getItem(k),progress);
 for(const network of ['Telegram','Instagram','Threads','Facebook','Max','ВКонтакте','WhatsApp','Pinterest']){const b=section.getByRole('button',{name:'Поделиться в '+network,exact:true});assert.equal(await b.getAttribute('title'),'Поделиться в '+network);const svg=b.locator('svg');assert.equal(await svg.getAttribute('width'),'24');assert.equal(await svg.getAttribute('height'),'24');await b.click();}
 assert.equal(publications,0);const shares=await page.evaluate(()=>window.shareCalls);assert.equal(shares.filter(x=>typeof x==='object'&&x.file==='image/jpeg').length,8);assert.equal(shares[0],'copy');
 await page.evaluate(()=>window.cancelShare=true);await section.getByRole('button',{name:'Поделиться',exact:true}).click();assert.equal(await page.getByText('Не удалось поделиться. Картинку и текст можно сохранить отдельно',{exact:true}).count(),0);await page.evaluate(()=>window.cancelShare=false);
 const dl=page.waitForEvent('download');await section.getByRole('button',{name:'Скачать картинку',exact:true}).click();assert.equal((await dl).suggestedFilename(),'espanolreal-post.jpg');
 await page.setViewportSize({width:1280,height:900});await section.getByRole('button',{name:'Поделиться в Facebook'}).click();await page.waitForFunction(()=>window.opened.some(x=>x.includes('facebook.com/sharer')));assert.equal(publications,1);const opens=await page.evaluate(()=>window.opened);assert.equal(opens[0],'about:blank');assert.ok(opens[1].includes(encodeURIComponent(base+'/p/')));
 for(const network of ['Telegram','Threads','Max','ВКонтакте','WhatsApp','Pinterest'])await section.getByRole('button',{name:'Поделиться в '+network,exact:true}).click();assert.equal(publications,1);assert.ok((await page.evaluate(()=>window.opened)).some(x=>x.includes('media%2Fposts')&&x.includes('pin.jpg')));
 await section.getByRole('button',{name:'Скопировать ссылку',exact:true}).click();assert.ok((await page.evaluate(()=>window.copied)).includes('/p/'));
 const insta=page.waitForEvent('download');await section.getByRole('button',{name:'Поделиться в Instagram'}).click();await insta;await page.getByText('Загрузите картинку в Instagram вручную',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Без мема',exact:true}).click();await page.waitForTimeout(500);await section.getByRole('button',{name:'Поделиться в Facebook'}).click();await page.waitForFunction(()=>window.opened.filter(x=>x.includes('facebook.com/sharer')).length===2);assert.equal(publications,2);
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'share overflow '+width)}
 await page.evaluate(()=>localStorage.setItem('espanol-real:interface-language','fr'));await page.reload();await page.getByRole('region',{name:'Partager',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Partager sur Telegram'}).count(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('espanol-real:interface-language')),'fr');
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),progress),before);assert.deepEqual(errors,[]);
 const id='bc92ec90-8897-43be-bd92-94419ffae82c';const response=await context.request.get(base+'/p/'+id);assert.equal(response.status(),200);const html=await response.text();assert.ok(html.includes('property="og:image"'));assert.ok(html.includes('/media/posts/'+id+'/og.jpg'));assert.ok(html.includes('name="twitter:card" content="summary_large_image"'));assert.equal(html.includes('content="noindex'),false);const image=await context.request.get(base+'/media/posts/'+id+'/og.jpg');assert.equal(image.status(),200);assert.equal(image.headers()['content-type'],'image/jpeg');
 console.log('Chromium: 8 accessible icons, prepared file/clipboard gesture, cancel/download, first-click popup+publication, 7 desktop intents, Instagram fallback, immutable revision, RU/FR persistence, responsive widths, exact course state and server HTML OG/media passed.');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
