import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
function load(path,aliases={},globals={}){const output=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(output,{exports,require:n=>n in aliases?aliases[n]:require(n),Buffer,process,URL,Response,Date,...globals});return exports}
const calls=[];const share=load('src/lib/share.ts',{}, {navigator:{canShare:()=>true,clipboard:{writeText:()=>{calls.push('copy');return Promise.resolve()}},share:async data=>{calls.push('share');assert.equal(data.files[0],file)}},setTimeout});const file={name:'post.jpg'};
assert.equal(share.supportsFileShare(file),true);await share.sharePreparedFile(file,'Title','Text',()=>{},()=>{});assert.deepEqual(calls,['copy','share']);
const data={id:'id',url:'https://example.com/p/id?a=1&b=2',imageUrl:'https://example.com/img.jpg',pinterestImageUrl:'https://example.com/pin.jpg'};
for(const platform of ['Telegram','Facebook','Threads','Max','Вконтакте','WhatsApp','Pinterest']){const u=new URL(share.desktopShareUrl(platform,data,'Café & ¿qué?','😀 texto & fin'));assert.ok(u.search.length);if(platform==='Pinterest')assert.equal(u.searchParams.get('media'),data.pinterestImageUrl);if(platform==='Facebook')assert.equal(u.searchParams.get('u'),data.url)}assert.equal(share.desktopShareUrl('Instagram',data,'',''),null);
const objects=new Map();const mem={set:async(k,v)=>objects.set(k,v),setJSON:async(k,v)=>objects.set(k,v),get:async k=>objects.get(k)??null,delete:async k=>objects.delete(k)};
const store=load('src/server/share/store.ts',{'server-only':{},'@netlify/blobs':{getStore:()=>mem},'./preview-fixture':{previewFixture:()=>null}});
const model=load('src/lib/teacher-posts/model.ts');const templates=load('src/server/teacher-posts/templates.ts');const examples=load('src/lib/teacher-posts/examples.ts').wowExamples;
const post=templates.templatePost({...model.emptyDraft,sourceText:examples[1].sourceText});const sharp=require('sharp');const image=await sharp({create:{width:700,height:1100,channels:3,background:'#9E2A2B'}}).jpeg().toBuffer();const input='data:image/jpeg;base64,'+image.toString('base64');
const first=await store.saveSnapshot({post,mode:'mock',cta:null},'QA','https://example.com',input);const second=await store.saveSnapshot({post:{...post,title:'changed'},mode:'mock',cta:null},'QA','https://example.com',input);assert.notEqual(first.id,second.id);assert.ok(store.validSnapshotId(first.id));assert.equal((await store.readSnapshot(first.id)).title,post.title);assert.equal((await store.readSnapshot(first.id)).post.visual.mediaUrl,first.imageUrl);assert.equal((await store.readSnapshot(first.id)).post.visual.uploadedImage,'');
for(const [name,w,h] of [['og.jpg',1200,630],['pin.jpg',1000,1500]]){const meta=await sharp(Buffer.from(objects.get(`media/${first.id}/${name}`))).metadata();assert.equal(meta.width,w);assert.equal(meta.height,h)}
await assert.rejects(store.saveSnapshot({post,mode:'mock',cta:null},'QA','https://example.com','data:image/svg+xml;base64,AA=='));assert.equal(await store.readSnapshot('../bad'),null);
const route=load('src/app/api/teacher/posts/share/route.ts',{'@/server/http':{currentUser:async()=>null,errorResponse:(error,status=400)=>({error,status}),rateLimit:()=>null,readJsonBody:async()=>null},'@/server/teacher-posts/origin':{samePostOrigin:()=>true},'@/lib/teacher-posts/model':model,'@/server/share/store':store});assert.equal((await route.POST({})).status,401);
console.log('Share URLs/encoding, synchronous clipboard→file gesture, sharp dimensions, immutable random IDs, original-specific image URLs, raster rejection and auth gate passed.');
